### ISSUE TITLE
Upon invalid_grant on mediatype=application/json, return 4XX instead of 200

### ISSUE THREAD

**Issue by vroldanbet** [zalando/planb-provider#76]
When user credentials are incorrect, a 200 OK is being returned by the backend. Return the correct status code 401.

**Comment by hjacobs** [comment]
Actually the backend does a redirect to the login form (status 302), it will only return status 200 if the "Accept" header specifies "application/json", in this case it returns a JSON with "redirect" property.

So I don't currently see where we have a bug?

**Comment by vroldanbet** [comment]
@hjacobs I think the issue manifests itself when the credentials are incorrect.

**Comment by artdaw** [comment]
Let me try to explain in details what this 'bug' means for me. Since I have SPA and I send "Accept" header = "application/json" in case of wrong credentials I still have 200 response with redirect url pointing to the access denied page. From my point of view it is better to have a 401 response when I send "Accept" header = "application/json" and credentials are wrong cause it that case I can display 'Wrong login' error message and don't need to parse redirect uri.

**Comment by danieldelhoyo** [comment]
for me it also makes sense to return a 401 for Accept header "application/json"
@hjacobs @vroldanbet any reason against it?

**Comment by vroldanbet** [comment]
See branch bug/76-return-4XX-upon-invalid-grant

**Comment by vroldanbet** [comment]
+1

**Comment by vroldanbet** [comment]
Fixed on commit 7a6616bb3dbeb884d3f599c12eff8441d51a9c65. Merged to master.
